---
title: "NER ANALYSIS"
author: "Shanet"
date: "2023-01-22"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(stringr)
```

```{r}
df=read.csv("GroupedwTIME.csv")
```

```{r}
ggplot(df,aes(x=Label,y=Clicks))+
  geom_point()+
  coord_flip()+
  theme_classic()+
  ggtitle("Mean amount of clicks by NER label")+
     annotate('text', x = 9, y = 325, label = '310')+
  annotate('text', x = 13, y = 460, label = '445')+
  annotate('text', x = 16, y = 490, label = '472')
```

```{r}
lengthdata <- read.csv("lengthcoded.csv")
pageviews <- read.csv("googleviews.csv")
pageviews$Day.Index <- as.Date(pageviews$Day.Index, format = "%m/%d/%y")
pageviews$Pageviews <- gsub(",","",pageviews$Pageviews)
pageviews$Pageviews <- as.numeric(pageviews$Pageviews)
```

```{r}
subsetted <- subset(lengthdata, Length > 25)
subsetted2 <- subset(subsetted, Length < 110)
```


```{r}
ggplot(subsetted2)+
  geom_bar(aes(x=Length,alpha =0.1), fill = "slateblue3") + 
  scale_x_continuous(breaks = seq(from = 30, to = 110, by = 20)) + geom_smooth(aes(x=Length,y=Clicks),colour="orange", linewidth = 2) + scale_y_log10() +
  labs(title = "Headline length vs. amount of Clicks", y = "log10(Clicks)")+
  theme_bw() + theme(legend.position = "NONE") 
```
```{r}
ggplot(pageviews,aes(x = Day.Index, y = Pageviews)) + geom_line(color = "slateblue3", alpha = 0.3, linewidth = 0.9) + geom_smooth(color = "orange", linewidth = 1.8) + labs(x = "Date", y = "Page views")
```
```{r}
df = read.csv("punct_text_ner.csv", sep = ';')
```

```{r}
max(df$count_punct)
```


```{r}
ggplot(df, 
       aes(x = count_punct, y = Clicks)) +
  geom_bar(stat = "identity",position="dodge") + scale_x_continuous(breaks = seq(0,23, by = 1)) +
  labs(title = "Punctuation versus clicks",
       x = "Number of punctuation characters",
       y = 'Clicks') + coord_flip() + theme_classic()
```




